name: Deploy Azure Function

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'src/demo-fn/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Deploy to Azure Function
        run: |
          if [ "${{ github.ref_name }}" == "dev" ]; then
            func azure functionapp publish demo-fn-dev
          elif [ "${{ github.ref_name }}" == "main" ]; then
            func azure functionapp publish demo-fn-prod
          fi